cgit script - general improvements

diff --git a/utils/cgit/cgit_prod_publish b/utils/cgit/cgit_prod_publish
--- a/utils/cgit/cgit_prod_publish
+++ b/utils/cgit/cgit_prod_publish
@@ -2,7 +2,7 @@
 
 # about: release to production
 
-BRANCH=`git branch --show-current`
+BRANCH=$(git branch --show-current)
 
 if [[ $BRANCH != *"release"* ]]; then
   echo "You are not on a release branch. Change to a release branch to perform this function."
@@ -15,9 +15,8 @@ echo ""
 echo ""
 echo "Congratulations on being ready to release to production."
 echo ""
-echo "I will check out the release branch $BRANCH and install this in"
-echo "PRODUCTION. I will then get the other branches, develop and master"
-echo "in sync."
+echo "I will check out the release branch $BRANCH and sync develop and master,"
+echo "then deploy to PRODUCTION."
 echo ""
 echo ""
 read -p "Press key to continue..." -n1 -s
@@ -35,38 +34,102 @@ then
   fi
 
   echo ""
+  echo "Syncing branches before deployment..."
+  echo ""
+
+  echo "Checking out develop branch..."
+  git checkout develop
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Pulling latest develop branch..."
+  git pull origin develop
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Merging $BRANCH into develop..."
+  git merge $BRANCH
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Pushing develop..."
+  git push origin develop
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Checking out master branch..."
+  git checkout master
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Pulling latest master branch..."
+  git pull origin master
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Merging $BRANCH into master..."
+  git merge $BRANCH
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo "Pushing master branch..."
+  git push origin master
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo ""
+  echo "Branches synced. Switching back to $BRANCH for deployment..."
+  echo ""
+
+  git checkout $BRANCH
+  if [ $? -ne 0 ];then
+   exit 1
+  fi
+
+  echo ""
   echo "Deploying to PRODUCTION server..."
   echo ""
 
-PRODENV=$(eb list | grep $CGIT_ENV-production)
-PRODNUM=$(eb list | grep $CGIT_ENV-production | wc -l)
+  PRODENV=$(eb list | grep $CGIT_ENV-production)
+  PRODNUM=$(eb list | grep $CGIT_ENV-production | wc -l)
 
-if [ "$PRODNUM" -eq 1 ]
-then
+  if [ "$PRODNUM" -eq 1 ]
+  then
+    # Capture current version for rollback hint
+    PREV_VERSION=$(aws elasticbeanstalk describe-environments \
+      --environment-names "$PRODENV" \
+      --query 'Environments[0].VersionLabel' \
+      --output text 2>/dev/null)
+
     # Get number of EC2 instances running. We want at least 2
     utils/cgit/_cgit_scale_environment_for_deployment $PRODENV
     ec2_instances=$?
 
-  echo "Original instance number was $ec2_instances"
+    echo "Original instance number was $ec2_instances"
 
-   echo "Deploying code to $PRODENV..."
-   DATE=$(date '+%a_%d/%m/%Y_%H:%M:%S')
-   eb deploy -m "$BRANCH@$DATE" $PRODENV
+    echo "Deploying code to $PRODENV..."
+    DATE=$(date '+%a_%d/%m/%Y_%H:%M:%S')
+    eb deploy -m "$BRANCH@$DATE" $PRODENV
 
-   if [ "$ec2_instances" = "1" ]
+    if [ "$ec2_instances" = "1" ]
     then
-
       echo "Restoring instance number to $ec2_instances. Could take a few minutes..."
-
       eb scale "$ec2_instances" "$PRODENV"
+    fi
 
-   fi
-
-else
-   echo "Cannot deploy to Production, found more than one Production environment."
-   echo $PRODENV
-fi
-
+  else
+    echo "Cannot deploy to Production, found more than one Production environment."
+    echo $PRODENV
+    exit 1
+  fi
 
   echo ""
   echo ""
@@ -80,81 +143,19 @@ else
   git status
   echo ""
   echo ""
-  exit
-fi
-
-echo ""
-echo "Checking out develop branch..."
-echo ""
-
-git checkout develop
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""
-echo "Pulling latest develop branch..."
-echo ""
-
-git pull origin develop
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""
-echo "Merging $BRANCH..."
-echo ""
-
-git merge $BRANCH
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""
-echo "Pushing develop..."
-echo ""
-
-git push origin develop
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""
-echo "Checking out master branch..."
-echo ""
-
-git checkout master
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""
-echo "Pulling latest master branch..."
-echo ""
-
-git pull origin master
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""   
-echo "Merging $BRANCH..."
-echo ""
-
-git merge $BRANCH
-if [ $? -ne 0 ];then
- exit 1
-fi
-
-echo ""
-echo "Pushing master branch..."
-echo ""
-
-git push origin master
-if [ $? -ne 0 ];then
- exit 1
+  exit 1
 fi
 
 echo ""
 echo "Running the smoke test..."
 cgit_prod_smoke_test
+
+echo ""
+echo "Deployment of $BRANCH complete."
+if [ -n "$PREV_VERSION" ]; then
+  echo ""
+  echo "Previous version was: $PREV_VERSION"
+  echo "To roll back if needed:"
+  echo "  eb deploy -l \"$PREV_VERSION\" $PRODENV"
+fi
+echo ""
diff --git a/utils/cgit/cgit_uat_publish b/utils/cgit/cgit_uat_publish
--- a/utils/cgit/cgit_uat_publish
+++ b/utils/cgit/cgit_uat_publish
@@ -49,6 +49,17 @@ if [ $? -ne 0 ];then
 fi
 
 echo ""
+echo "Running unit tests before creating release..."
+echo ""
+cgit_dev_test_unit
+if [ $? -ne 0 ]; then
+  echo ""
+  echo "Unit tests failed. Fix the failures before releasing to UAT."
+  exit 1
+fi
+echo "Tests passed."
+
+echo ""
 echo "Updating release version in $CGIT_ENV code..."
 echo ""
 
@@ -101,6 +112,12 @@ UATNUM=$(eb list | grep $COBALT_UAT | wc -l)
 
 if [ "$UATNUM" -eq 1 ]
 then
+    # Capture current version for rollback hint
+    PREV_VERSION=$(aws elasticbeanstalk describe-environments \
+      --environment-names "$UATENV" \
+      --query 'Environments[0].VersionLabel' \
+      --output text 2>/dev/null)
+
     # Get number of EC2 instances running. We want at least 2
     utils/cgit/_cgit_scale_environment_for_deployment $UATENV
     ec2_instances=$?
@@ -119,6 +136,16 @@ then
       eb scale "$ec2_instances" "$UATENV"
 
    fi
+
+   echo ""
+   echo "Deployment of release/$RELEASE to UAT complete."
+   if [ -n "$PREV_VERSION" ]; then
+     echo ""
+     echo "Previous version was: $PREV_VERSION"
+     echo "To roll back if needed:"
+     echo "  eb deploy -l \"$PREV_VERSION\" $UATENV"
+   fi
+   echo ""
 
 else
    echo "Cannot deploy to UAT, found more than one UAT environment."
